var user = new Object();
var parser = new UAParser();
var jsscreen = screen.width + 'x' + screen.height; if ( screen.pixelDepth ) jsscreen += " ("+screen.pixelDepth+")";
user.env = {'resolution' : screen.pixelDepth,'userAgent' : navigator.userAgent,'appName': navigator.appName,'browser' : parser.getBrowser(),'os' : parser.getOS(),'screen': jsscreen,'engine': parser.getEngine(),'cpu': parser.getCPU(),'device': parser.getDevice()};
var sOapp = user.env.os.name.substr(0,3);
sOapp = (sOapp.toLowerCase() == 'ios') ? 'ios' : 'android';
user.trace = 'home';
user.typeWeb = 'app';
user.terminos = 'No';
user.img = ['','','',''];
var nombreApp = 'ReyPlata';
var urlSendForm = "http://e-short.com/apps/reyplata/php/registra_formulario.php";
var urlUploadPhoto = "http://e-short.com/apps/reyplata/php/uploadPhoto.php";
var urlinAppBrowser = 'http://reyplata.com';
var pictureSource;   // picture source
var destinationType; // sets the format of returned value
var numPhoto = 0;
var cargandoPhoto = 0;
var photosCamera = ['','','',''];
var comprobandoDatos = 0;
var txt_error_nombre_vacio = "Nombre requerido";
var txt_error_cp_vacio = "CP requerido";
var txt_error_cp_error = "CP erróneo";
var txt_error_telefono_vacio = "Teléfono requerido";
var txt_error_telefono_error = "Teléfono incorrecto";
var txt_error_email_vacio = "E-mail requerido";
var txt_error_email_novalido = "E-mail no válido";
var txt_error_objeto_vacio = "Objeto a tasar requerido";
var txt_error_terminos = "Debes aceptar los términos";
var txt_error_register = "Error en el registro";
var txt_btn_aceptar = "Aceptar";
var txt_btn_cancelar = "Cancelar";
var txt_btn_si = "Si";
var txt_btn_no = "No";
var txt_error_data_noImage = "¿Enviar los datos sin imágenes?";
var txt_msj_register = "Datos enviados con éxito\n\n¿Deseas solicitar otra tasación?";
var txt_error_uploadPhoto = "Error al cargar imagen";
var txt_msj_borrarLoc = "¿Quieres modificar los datos?";
var mail_recAmigo_subject = "Vende fácil y con el mejor precio tus objetos de Oro, Plata, Platino y Diamantes.";
var mail_recAmigo_body = "Te recomiendo esta aplicación que te permitirá vender fácil y con el mejor precio todos los objetos de Oro y Plata que ya no usas.<br/><br/>Si quieres saber cuánto te pagarían por ellos no lo dudes y descárgatela en: http://reyplata.com/apps";
var iabRef;
var loadpage = 0;
var iabMail;